COLUMNS:
  Clientnum: int64
  Attrition: object
  Age: int64
  Gender: object
  Dependent_count: int64
  Education: object
  Marital_Status: object
  Income: object
  Card_Category: object
  Months_on_book: int64
  Total_Relationship_Count: int64
  Months_Inactive: int64
  Contacts_Count: int64
  Credit_Limit: float64
  Total_Revolving_Bal: int64
  Avg_Open_To_Buy: float64
  Total_Amt_Chng_Q4_Q1: float64
  Total_Trans_Amt: int64
  Total_Trans_Ct: int64
  Total_Ct_Chng_Q4_Q1: float64
  Avg_Utilization_Ratio: float64

TARGET_COLUMN:
  name: Attrition
