# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - churnapplicationnewlatest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://churnrepositoryimagename.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d0beeab0c22640978e2e64a1001a8568 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_16ea1847eb5b459392b9f3fa558a2b34 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: churnrepositoryimagename.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d0beeab0c22640978e2e64a1001a8568 }}/churn_app2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'churnapplicationnewlatest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2ca8f62e38414d0494a38aac4be62a7d }}
        images: 'churnrepositoryimagename.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d0beeab0c22640978e2e64a1001a8568 }}/churn_app2:${{ github.sha }}'